# Site settings
title: Research On Knowing LLC
email: info@researchonknowing.com
favicon: '/img/laptop.ico'
url: https://www.researchonknowing.com 
description: "The practical application of epistemology to advance how we learn, understand and create things."
# Disable non-whitelisted plugins, caching to disk, and ignore symbolic links.
safe: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#FFFFFF'
# Footer settings
footer: Research On Knowing LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/jamieonknowing
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/Research-on-Knowing

# Build settings
markdown: kramdown
remote-theme: jeromelachaud/grayscale-theme
permalink: pretty
# lsi latent symentic indexing of posts using classifier-reborn plugin.
lsi: false
# incremental rebuild of only changed pages and posts
incremental: false
