# Site settings
title: Research On Knowing LLC
# favicon: 'assets/images/favicon.ico'
email: info@researchonknowing.com
url: https://www.researchonknowing.com 
description: "Reinventing computer programming to revolutionize how we learn, understand and create."
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#FFFFFF'
# Footer settings
footer: Research On Knowing LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/jamieonknowing
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/Research-on-Knowing

# Build settings
markdown: kramdown
remote-theme: jeromelachaud/grayscale-theme
permalink: pretty